name: Deploy to Staging

on:
  push:
    branches:
      - staging  # or your default branch like 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

    #   - name: Run tests
    #     run: npm test
